socket_type = "tcp"
socket_path = "127.0.0.1:9200"
cache_seconds = 5
neg_cache_seconds = 2
use_etag = true
#use_serialized_auth = false
auth_realm = "TEST Authentication"
#user_agent = "ngx_auth_mod"

[response.ok]
#code=200
message="Authorized0"

[[switch]]
username_re = '^[^@]+$'
auth_url = "http://127.0.0.1:9300"
set_username = "$0"
set_password = "$p"
#skip_cert_verify = false
#root_ca_files = [
#	"/etc/ssl/certs/Local-CA-Chain.cer",
#]
timeout = 5000

[switch.set_header]
"X-Remote-User" = "$u"

[switch.response.unauth]
#code=401
message="Not authenticated1"

[switch.response.forbidden]
#code=403
message="Forbidden1"

[switch.response.bad_request]
#code=400
message="Bad request1"

[switch.response.bad_gateway]
#code=501
message="Bad gateway1"

[switch.response.timeout]
#code=504
message="Timeout1"

[switch.response.invalid_setting]
#code=500
message="Invalid setting1"

[[switch]]
username_re = '^([^@]+)@example\.com$'
auth_url = "http://127.0.0.1:9200"
set_username = "$1"
set_password = "$p"
#skip_cert_verify = false
#root_ca_files = [
#	"/etc/ssl/certs/Local-CA-Chain.cer",
#]
timeout = 5000

[switch.set_header]
"X-Remote-User" = "$u"

[switch.response.unauth]
#code=401
message="Not authenticated2"

[switch.response.forbidden]
#code=403
message="Forbidden2"

[switch.response.bad_request]
#code=400
message="Bad request2"

[switch.response.bad_gateway]
#code=502
message="Bad gateway2"

[switch.response.timeout]
#code=504
message="Timeout2"

[switch.response.invalid_setting]
#code=500
message="Invalid setting2"
