socket_type = "tcp"
socket_path = "127.0.0.1:9200"
cache_seconds = 15
neg_cache_seconds = 2
use_etag = true
#use_serialized_auth = false
auth_realm = "TEST Authentication"

#user_agent = "ngx_auth_mod"
#username_re = '^(.*)@example\.com$'
auth_url = "http://auth.example.com/"
#skip_cert_verify = true
root_ca_files = [
	"/etc/ssl/certs/Local-CA-Chain.cer",
]
#timeout = 1000

set_username = "$1"
set_password = "$p"

[set_header]
"X-Forwarded-User" = "$u"

#[response.ok]
#code=200
#message="Authorized"

#[response.unauth]
#code=401
#message="Not authenticated Test"

#[response.forbidden]
#code=403
#message="Forbidden"

#[response.bad_request]
#code=400
#message="Bad request"

#[response.bad_gateway]
#code=502
#message="Bad gateway"

#[response.timeout]
#code=504
#message="Timeout"

#[response.invalid_setting]
#code=500
#message="Invalid setting"
